import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion'
import { Accessibility, ArrowDown, ArrowUpRight, Camera, Check, ChevronRight, Menu, Play, RotateCcw, Search, Send, Upload, Volume2, X, Zap } from 'lucide-react'
import { actions, alphabet, challenges, creators, cultures, signs, stories } from './data/content'
import './App.css'
import './action.css'
import './gesture.css'
import './camera.css'
import './finger-hand.css'
import './gesture-profiles.css'
import './reference.css'
import './practice.css'
import './word-poses.css'

const fadeUp = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: 0.65 } } }

function App() {
  const { scrollYProgress } = useScroll()
  const heroY = useTransform(scrollYProgress, [0, 0.25], [0, 100])
  const [activeSign, setActiveSign] = useState(signs[0])
  const [activeStory, setActiveStory] = useState(stories[0])
  const [activeCulture, setActiveCulture] = useState(cultures[0])
  const [activeCategory, setActiveCategory] = useState('All')
  const [learningMode, setLearningMode] = useState('words')
  const [activeLetter, setActiveLetter] = useState(alphabet[0])
  const [musicOn, setMusicOn] = useState(false)
  const [cameraOn, setCameraOn] = useState(false)
  const [cameraError, setCameraError] = useState('')
  const [detectedSign, setDetectedSign] = useState('')
  const videoRef = useRef(null)
  const streamRef = useRef(null)
  const [challengeIndex, setChallengeIndex] = useState(0)
  const [challengeDone, setChallengeDone] = useState(false)
  const [highContrast, setHighContrast] = useState(false)
  const [largeText, setLargeText] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [signInOpen, setSignInOpen] = useState(false)
  const [signedIn, setSignedIn] = useState(false)
  const [published, setPublished] = useState(false)
  const [languageIndex, setLanguageIndex] = useState(0)
  const [lastAction, setLastAction] = useState('Ready for your first move')
  const [completedActions, setCompletedActions] = useState([])
  const [search, setSearch] = useState('')

  const categories = ['All', ...new Set(signs.map((sign) => sign.category))]
  const visibleSigns = signs.filter((sign) => (activeCategory === 'All' || sign.category === activeCategory) && sign.name.toLowerCase().includes(search.toLowerCase()))
  const handleAction = (label) => { setLastAction(label); setCompletedActions((current) => current.includes(label) ? current : [...current, label]) }
  const jumpTo = (id, label = `Opened ${id}`) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false); handleAction(label) }
  const practiceLetter = () => { setDetectedSign(activeLetter.letter); setCameraOn(true); jumpTo('ai', `Practising letter ${activeLetter.letter}`) }
  const handleMainClick = (event) => { const button = event.target.closest('button'); if (button?.textContent.includes('TRY THE MOVEMENT')) { setDetectedSign(activeSign.name); setCameraOn(true); jumpTo('ai', `Practising ${activeSign.name}`) } }

  useEffect(() => {
    if (!cameraOn) {
      streamRef.current?.getTracks().forEach((track) => track.stop())
      streamRef.current = null
      if (videoRef.current) videoRef.current.srcObject = null
      return undefined
    }

    let cancelled = false
    navigator.mediaDevices?.getUserMedia({ video: { facingMode: 'user' }, audio: false }).then((stream) => {
      if (cancelled) {
        stream.getTracks().forEach((track) => track.stop())
        return
      }
      streamRef.current = stream
      if (videoRef.current) videoRef.current.srcObject = stream
      setDetectedSign(activeSign.name)
      handleAction('Camera detected HELLO (demo)')
    }).catch(() => setCameraError('Camera permission was blocked. Allow camera access in your browser and try again.'))

    return () => {
      cancelled = true
      streamRef.current?.getTracks().forEach((track) => track.stop())
    }
  }, [cameraOn, activeSign.name])

  return (
    <main onClick={handleMainClick} className={`${highContrast ? 'high-contrast ' : ''}${largeText ? 'large-text ' : ''}${reducedMotion ? 'reduced-motion' : ''} site-shell`}>
      <motion.div className="scroll-progress" style={{ scaleX: scrollYProgress }} />
      <header className="nav-wrap">
        <nav className="navbar" aria-label="Main navigation"><button className="wordmark" onClick={() => jumpTo('top', 'Returned home')}><span className="wordmark-dot" />SIGNVERSE</button><div className={`nav-links ${menuOpen ? 'open' : ''}`}><button onClick={() => jumpTo('discover', 'Opened discovery')}>Discover</button><button onClick={() => jumpTo('experience', 'Opened experience')}>Experience</button><button onClick={() => jumpTo('culture', 'Opened culture')}>Culture</button><button onClick={() => jumpTo('stories', 'Opened stories')}>Stories</button><button onClick={() => jumpTo('community', 'Opened community')}>Community</button></div><div className="nav-actions"><button className="nav-icon" title="Accessibility settings" onClick={() => jumpTo('accessibility', 'Opened accessibility')}><Accessibility size={17} /></button><button className="nav-lang" type="button" onClick={() => { setLanguageIndex((languageIndex + 1) % 3); handleAction('Switched language') }}>EN {languageIndex > 0 ? `· ${languageIndex === 1 ? 'HI' : 'TA'}` : ''} <ChevronRight size={13} /></button><button className="nav-cta" type="button" onClick={() => { setSignInOpen(true); handleAction('Opened sign-in') }}>{signedIn ? 'MY SIGNVERSE' : 'ENTER SIGNVERSE'} <ArrowUpRight size={15} /></button><button className="menu-toggle" onClick={() => { setMenuOpen(!menuOpen); handleAction('Opened menu') }} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></nav>
      </header>

      <section className="practice-panel section-pad" aria-label="Selected sign practice"><div className="practice-copy"><p className="kicker dark-kicker"><span /> PRACTICE THIS SIGN</p><h2>Letter <em>{activeLetter.letter}</em><br />in three moves.</h2><p>Study the hand shape, follow the motion stages, then open your own camera to check your position.</p><button className="button button-coral" onClick={practiceLetter}>OPEN MY CAMERA <Camera size={16} /></button></div><div className="movement-steps"><div className="movement-step"><span>01 / SHAPE</span><span className="reference-hand practice-hand pose-letter"><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span></div><div className="movement-step"><span>02 / MOVE</span><span className="reference-hand practice-hand pose-letter stage-two"><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span></div><div className="movement-step"><span>03 / HOLD</span><span className="reference-hand practice-hand pose-letter stage-three"><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span></div></div></section>

      <section className="reference-lab section-pad" id="reference"><div className="section-header"><div><p className="kicker dark-kicker"><span /> SIGN REFERENCE LAB</p><h2>Know the word.<br /><em>See the movement.</em></h2></div><p className="section-note">Use the word cards for meaning.<br />Switch to A–Z for finger positions.</p></div><div className="mode-switch"><button className={learningMode === 'words' ? 'mode-button active' : 'mode-button'} onClick={() => { setLearningMode('words'); handleAction('Opened word signs') }}>WORD SIGNS</button><button className={learningMode === 'alphabet' ? 'mode-button active' : 'mode-button'} onClick={() => { setLearningMode('alphabet'); handleAction('Opened A-Z movements') }}>A–Z MOVEMENTS</button></div>{learningMode === 'words' ? <div className="word-reference-grid">{signs.map((sign) => <button className={activeSign.name === sign.name ? 'word-reference active' : 'word-reference'} key={sign.name} onClick={() => { setActiveSign(sign); handleAction(`Opened ${sign.name} movement`) }}><span className={`reference-hand pose-${sign.color}`}><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span><b>{sign.name}</b><small>{sign.category} / movement</small></button>)}</div> : <div className="alphabet-reference"><div className="alphabet-selected"><span className="reference-hand large pose-letter"><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span><div><span className="eyebrow-number">SELECTED MOVEMENT / {activeLetter.code}</span><h3>Letter {activeLetter.letter}</h3><p>Match the finger shape shown here, then check your hand in the camera.</p></div></div><div className="alphabet-grid">{alphabet.map((item) => <button className={activeLetter.letter === item.letter ? 'letter-card active' : 'letter-card'} key={item.letter} onClick={() => { setActiveLetter(item); setDetectedSign(item.letter); handleAction(`Selected letter ${item.letter}`) }}><span className={`reference-hand mini pose-letter-${item.letter}`}><i className="reference-palm" /><i className="reference-finger ref-a" /><i className="reference-finger ref-b" /><i className="reference-finger ref-c" /><i className="reference-thumb" /></span><b>{item.letter}</b><small>{item.code}</small></button>)}</div></div>}</section>

      <section className="hero" id="top"><motion.div className="hero-glow" style={{ y: heroY }} /><div className="hero-grid" /><div className="hero-copy"><motion.p className="kicker" initial="hidden" animate="show" variants={fadeUp}><span /> AN IMMERSIVE CULTURAL PLATFORM</motion.p><motion.h1 initial="hidden" animate="show" variants={fadeUp}>Some languages<br />are <em>heard.</em><br />Some are <strong>seen.</strong></motion.h1><p className="hero-sub">Discover Indian Sign Language as a living world of stories, expression, identity and culture.</p><div className="hero-buttons"><button className="button button-light" onClick={() => jumpTo('experience', 'Entered the world')}>ENTER THE WORLD <ArrowUpRight size={16} /></button><button className="text-button" onClick={() => jumpTo('discover', 'Explored SignVerse')}>EXPLORE SIGNVERSE <ArrowDown size={15} /></button></div></div><motion.div className="hero-hand" initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1 }}><div className="hand-orb" /><div className="hero-hand-shape">✋</div><span className="hero-word word-story">STORY</span><span className="hero-word word-identity">IDENTITY</span><span className="hero-word word-expression">EXPRESSION</span><span className="hero-word word-culture">CULTURE</span><span className="hero-word word-community">COMMUNITY</span></motion.div><button className="scroll-cue" onClick={() => jumpTo('discover', 'Scrolled to discover')}>SCROLL TO DISCOVER <ArrowDown size={14} /></button></section>

      <section className="hook section-pad" id="discover"><motion.div className="section-intro" initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp}><p className="kicker dark-kicker"><span /> CHANGE THE WAY YOU THINK</p><h2>What if language<br />didn't need <em>sound?</em></h2></motion.div><div className="compare-grid"><motion.div className="compare-card spoken" whileHover={{ y: -7 }}><span className="compare-index">01 / WHAT WE KNOW</span><h3>Language<br /><em>as we know it.</em></h3><div className="compare-pills"><span>SPOKEN</span><span>HEARD</span><span>WRITTEN</span></div></motion.div><motion.div className="compare-card signed" whileHover={{ y: -7 }}><span className="compare-index">02 / A NEW LENS</span><h3>Language<br /><em>as sign.</em></h3><div className="compare-pills"><span>SEEN</span><span>FELT</span><span>EXPRESSED</span></div></motion.div></div><p className="big-statement">Sign language isn't silence.<br /><strong>It is another way of speaking.</strong></p></section>

      <section className="experience section-pad dark-section" id="experience"><div className="section-header"><div><p className="kicker"><span /> THE FIRST HELLO</p><h2>Don't just learn a sign.<br /><em>Experience it.</em></h2></div><p className="section-note">A sign is never just a word.<br />It carries a world with it.</p></div><div className="sign-feature"><div className="feature-visual"><div className={`feature-glyph glyph-${activeSign.color}`}><div className={`sign-hand gesture-${activeSign.name.toLowerCase()}`} aria-label={`Animated finger movement for ${activeSign.name}`}><i className="sign-palm" /><i className="sign-thumb" /><i className="sign-finger finger-a" /><i className="sign-finger finger-b" /><i className="sign-finger finger-c" /><i className="sign-finger finger-d" /><i className="sign-finger finger-e" /></div></div><div className="feature-ring ring-a" /><div className="feature-ring ring-b" /><button className="replay-button" onClick={() => setActiveSign({ ...activeSign })}><RotateCcw size={14} /> REPLAY FINGER MOTION</button></div><div className="feature-copy"><span className="eyebrow-number">{String(signs.indexOf(activeSign) + 1).padStart(2, '0')} / {activeSign.category.toUpperCase()}</span><h3>{activeSign.name}</h3><p>{activeSign.context}</p><div className="feature-actions"><button className="button button-coral" onClick={() => setActiveSign(activeSign)}>TRY THE MOVEMENT <ArrowUpRight size={16} /></button><button className="sound-button" title="Play pronunciation"><Volume2 size={18} /></button></div><div className="sign-progress"><span /><span /><span /><span /></div></div></div><div className="sign-row">{signs.slice(0, 6).map((sign) => <button className={activeSign.name === sign.name ? 'mini-sign active' : 'mini-sign'} key={sign.name} onClick={() => setActiveSign(sign)}><span>{sign.icon}</span><b>{sign.name}</b><small>{sign.category}</small></button>)}</div></section>

      <section className="library section-pad" id="library"><div className="section-header"><div><p className="kicker dark-kicker"><span /> YOUR LIVING DICTIONARY</p><h2>Find a sign.<br /><em>Find a feeling.</em></h2></div><div className="library-search"><Search size={16} /><input aria-label="Search signs" placeholder="Search the library" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div><div className="filter-row">{categories.map((category) => <button className={activeCategory === category ? 'filter active' : 'filter'} key={category} onClick={() => setActiveCategory(category)}>{category}</button>)}</div><div className="library-grid">{visibleSigns.map((sign) => <button className="library-card" key={sign.name} onClick={() => { setActiveSign(sign); jumpTo('experience') }}><span className={`library-icon icon-${sign.color}`}>{sign.icon}</span><span><b>{sign.name}</b><small>{sign.context}</small></span><ArrowUpRight size={16} /></button>)}</div></section>

      <section className="stories section-pad dark-section" id="stories"><div className="section-header"><div><p className="kicker"><span /> SIGN STORIES</p><h2>Every sign<br /><em>has a story.</em></h2></div><p className="section-note">Small gestures.<br />Infinite meaning.</p></div><div className="story-grid">{stories.map((story) => <motion.button className={`story-card ${story.tone}`} key={story.title} whileHover={{ scale: 1.02 }} onClick={() => setActiveStory(story)}><span className="story-meta">{story.tag}</span><span className="story-title">{story.title}</span><span className="story-text">{story.text}</span><span className="story-link">EXPLORE STORY <ArrowUpRight size={15} /></span></motion.button>)}</div><AnimatePresence mode="wait"><motion.div className="story-detail" key={activeStory.title} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><span className="detail-label">NOW PLAYING / {activeStory.tag}</span><p>“{activeStory.text}”</p><button className="text-button coral-text">WATCH THE STORY <Play size={14} /></button></motion.div></AnimatePresence></section>

      <section className="culture section-pad" id="culture"><div className="section-header"><div><p className="kicker dark-kicker"><span /> THE CULTURE INSIDE</p><h2>The world inside<br /><em>sign language.</em></h2></div><div className="culture-feature"><span className="culture-feature-icon">{activeCulture.icon}</span><div><b>{activeCulture.title}</b><p>{activeCulture.text}</p></div></div></div><div className="culture-grid">{cultures.map((culture) => <button className={activeCulture.title === culture.title ? 'culture-card active' : 'culture-card'} key={culture.title} onClick={() => setActiveCulture(culture)}><span>{culture.icon}</span><b>{culture.title}</b><ChevronRight size={17} /></button>)}</div></section>

      <section className="music-section dark-section section-pad"><div className="music-copy"><p className="kicker"><span /> A SENSORY EXPERIMENT</p><h2>Can you feel music<br />without <em>hearing it?</em></h2><p>Rhythm becomes movement. Movement becomes expression. Expression becomes sign.</p><button className="button button-coral" onClick={() => setMusicOn(!musicOn)}>{musicOn ? 'PAUSE EXPERIENCE' : 'START EXPERIENCE'} {musicOn ? <Volume2 size={16} /> : <Play size={16} />}</button></div><div className={musicOn ? 'wave-field playing' : 'wave-field'} aria-label="Interactive music visualization"><div className="wave-labels"><span>BEAT</span><span>MOVE</span><span>EXPRESS</span><span>SIGN</span></div>{Array.from({ length: 18 }, (_, index) => <i key={index} style={{ '--i': index }} />)}</div></section>

      <section className="ai-section section-pad" id="ai"><div className="section-header"><div><p className="kicker dark-kicker"><span /> PROTOTYPE / COMPUTER VISION</p><h2>Your camera<br /><em>understands.</em></h2></div><p className="section-note">A playful glimpse at what<br />technology can make possible.</p></div><div className="ai-grid"><div className={cameraOn ? 'camera-preview on' : 'camera-preview'}><video ref={videoRef} className="camera-video" autoPlay muted playsInline aria-label="Live camera preview" /><div className="camera-corner top-left" /><div className="camera-corner top-right" /><div className="camera-corner bottom-left" /><div className="camera-corner bottom-right" />{cameraOn ? <><div className="camera-scan" /><span className="camera-badge">LIVE CAMERA / DEMO MODE</span></> : <><Camera size={34} /><p>Camera preview</p><small>Your browser will ask for permission.</small></>}{cameraError && <p className="camera-error">{cameraError}</p>}<button className="camera-start" onClick={() => { setCameraOn(!cameraOn); handleAction(cameraOn ? 'Stopped camera' : 'Opened camera') }}>{cameraOn ? 'STOP CAMERA' : 'OPEN CAMERA'} <Camera size={14} /></button></div><div className="detector-result"><span className="eyebrow-number">DETECTED SIGN</span><h3>{detectedSign || '— — —'}</h3><div className="confidence"><span>CONFIDENCE</span><b>{detectedSign ? '92%' : 'WAITING'}</b><i><em style={{ width: detectedSign ? '92%' : '0%' }} /></i></div><p>{detectedSign ? `${detectedSign} displayed in demo mode. The live camera is working; connect MediaPipe or TensorFlow here for real gesture recognition.` : 'Open the camera and show a sign to begin the prototype.'}</p><div className="feature-actions"><button className="button button-dark" onClick={() => { setCameraOn(false); setTimeout(() => setCameraOn(true), 50); handleAction('Tried camera again') }}>TRY AGAIN <RotateCcw size={14} /></button><button className="text-button" onClick={() => jumpTo('experience', 'Learned sign meaning')}>LEARN MORE <ArrowUpRight size={14} /></button></div></div></div></section>

      <section className="challenge-section dark-section section-pad" id="challenges"><div className="section-header"><div><p className="kicker"><span /> TODAY'S INVITATION</p><h2>Can you speak<br />without <em>speaking?</em></h2></div><div className="player-level"><span><Zap size={14} /> SIGN EXPLORER</span><b>LEVEL 04</b><small>1,240 XP</small></div></div><div className="challenge-layout"><div className="challenge-card"><span className="challenge-number">CHALLENGE #{String(challengeIndex + 1).padStart(2, '0')}</span><h3>Express <em>“{challenges[challengeIndex]}”</em></h3><div className="challenge-progress"><i style={{ width: `${((challengeIndex + (challengeDone ? 1 : 0)) / challenges.length) * 100}%` }} /></div><div className="challenge-actions"><button className="button button-coral" onClick={() => setChallengeDone(true)}>{challengeDone ? <><Check size={15} /> COMPLETED</> : <>I'M READY <ArrowUpRight size={15} /></>}</button><button className="skip-button" onClick={() => { setChallengeIndex((challengeIndex + 1) % challenges.length); setChallengeDone(false) }}>SKIP <ChevronRight size={15} /></button></div></div><div className="achievement-list"><span className="eyebrow-number">ACHIEVEMENTS</span><div><span className="achievement unlocked">🌱</span><span className="achievement">🔥</span><span className="achievement">🌎</span><span className="achievement">🤝</span><span className="achievement">⭐</span></div><small>FIRST SIGN &nbsp; · &nbsp; 7 DAY EXPLORER &nbsp; · &nbsp; CULTURE BUILDER</small></div></div></section>

      <section className="map-section section-pad" id="community"><div className="section-header"><div><p className="kicker dark-kicker"><span /> A GLOBAL CONVERSATION</p><h2>One world.<br /><em>Many ways to sign.</em></h2></div><p className="section-note">Sign languages are not universal.<br />Each one has its own identity.</p></div><div className="map-board"><div className="map-lines" /><div className="map-globe">◎</div><button className="map-pin pin-india" title="Indian Sign Language">IN</button><button className="map-pin pin-usa" title="American Sign Language">US</button><button className="map-pin pin-uk" title="British Sign Language">UK</button><div className="map-callout"><span>NOW EXPLORING</span><b>🇮🇳 Indian Sign Language</b><p>A language with its own community, grammar and visual identity.</p><button className="text-button coral-text">DISCOVER ISL <ArrowUpRight size={14} /></button></div></div></section>

      <section className="community-section dark-section section-pad"><div className="section-header"><div><p className="kicker"><span /> MEET THE COMMUNITY</p><h2>The people<br /><em>behind the signs.</em></h2></div><p className="section-note">Deaf creators. Artists.<br />Teachers. Inventors.</p></div><div className="creator-grid">{creators.map((creator) => <article className="creator-card" key={creator.name}><div className={`creator-avatar ${creator.color}`}>{creator.initials}</div><span className="creator-role">{creator.role}</span><h3>{creator.name}</h3><p>“My favourite sign is <b>{creator.sign}</b>.”</p><button className="text-button" onClick={() => setActiveStory(stories[0])}>WATCH STORY <Play size={13} /></button></article>)}</div><div className="creator-studio"><div><span className="eyebrow-number">CREATOR STUDIO</span><h3>Create without words.</h3><p>Share a short sign-language story with the world.</p></div>{published ? <span className="published-message"><Check size={16} /> STORY READY TO SHARE</span> : <button className="button button-light" onClick={() => setPublished(true)}><Upload size={15} /> UPLOAD A STORY</button>}</div></section>

      <section className="accessibility-section section-pad" id="accessibility"><div><p className="kicker dark-kicker"><span /> BUILT FOR EVERY BODY</p><h2>Access is not a setting.<br /><em>It is the starting point.</em></h2></div><div className="access-controls"><button className={highContrast ? 'access-control on' : 'access-control'} onClick={() => setHighContrast(!highContrast)}><span><Accessibility size={18} /></span><b>High contrast</b><small>{highContrast ? 'On' : 'Off'}</small></button><button className={largeText ? 'access-control on' : 'access-control'} onClick={() => setLargeText(!largeText)}><span>Aa</span><b>Large text</b><small>{largeText ? 'On' : 'Off'}</small></button><button className={reducedMotion ? 'access-control on' : 'access-control'} onClick={() => setReducedMotion(!reducedMotion)}><span>◌</span><b>Reduce motion</b><small>{reducedMotion ? 'On' : 'Off'}</small></button></div></section>

      <section className="action-deck section-pad" id="actions"><div className="section-header"><div><p className="kicker dark-kicker"><span /> INTERACTION INDEX</p><h2>Everything here<br /><em>can respond.</em></h2></div><div className="action-score"><strong>{completedActions.length}<span>/</span>{actions.length}</strong><small>ACTIONS EXPLORED</small></div></div><div className="action-status"><span className="status-pulse" /> <b>LAST ACTION</b><span>{lastAction}</span><button className="text-button" onClick={() => { setCompletedActions([]); setLastAction('Action history cleared'); }}>CLEAR HISTORY <X size={13} /></button></div><div className="action-grid">{actions.map((action, index) => <button className={completedActions.includes(action) ? 'action-chip complete' : 'action-chip'} type="button" key={action} onClick={() => handleAction(action)}><span>{completedActions.includes(action) ? <Check size={13} /> : String(index + 1).padStart(2, '0')}</span>{action}<ArrowUpRight size={13} /></button>)}</div></section>

      <section className="final-section"><div className="final-glow" /><p className="kicker"><span /> THE INVITATION</p><h2>You didn't come here<br />to learn a language.</h2><h3>You came to <em>discover a world.</em></h3><p className="final-line">And now you can see it.</p><div className="hero-buttons"><button className="button button-light" onClick={() => { setSignInOpen(true); handleAction('Entered SignVerse again') }}>ENTER SIGNVERSE <ArrowUpRight size={16} /></button><button className="text-button" onClick={() => { navigator.clipboard?.writeText(window.location.href); handleAction('Shared experience') }}>SHARE THE EXPERIENCE <Send size={14} /></button></div></section>

      <footer className="footer"><div><button className="wordmark" onClick={() => jumpTo('top')}><span className="wordmark-dot" />SIGNVERSE</button><p>See the world differently.</p></div><div className="footer-links"><button onClick={() => jumpTo('discover')}>Explore</button><button onClick={() => jumpTo('stories')}>Stories</button><button onClick={() => jumpTo('community')}>Community</button><button onClick={() => jumpTo('accessibility')}>Accessibility</button></div><span>Built to make language visible.</span></footer>

      {signInOpen && <div className="modal-backdrop" onClick={(event) => event.target === event.currentTarget && setSignInOpen(false)}><div className="signin-modal" role="dialog" aria-modal="true" aria-labelledby="signin-heading"><button className="modal-close" onClick={() => setSignInOpen(false)} aria-label="Close"><X size={18} /></button><span className="wordmark-dot" /><h2 id="signin-heading">Enter the<br /><em>world.</em></h2><p>Save signs, track challenges and make this world yours.</p><input type="email" placeholder="Your email address" aria-label="Email address" /><button className="button button-coral" onClick={() => { setSignedIn(true); setSignInOpen(false) }}>CONTINUE <ArrowUpRight size={15} /></button><small>Demo sign-in for the hackathon experience.</small></div></div>}
    </main>
  )
}

export default App
